version: 1.0.{build}

configuration: Release
platform: x64

init:
  - ps: |
      If ($env:Platform -Match "x86") {
        $env:ARCHITECTURE="32"
      } Else {
        $env:ARCHITECTURE="64"
        $env:GENERATOR_SUFFIX=" Win64"
      }

      $env:LIB_ARCHITECTURE="lib$($env:ARCHITECTURE)"
      $env:WINDOWS_ARCHITECTURE="win$($env:ARCHITECTURE)"

      $env:BOOST_ROOT="C:/Libraries/boost_$($env:BOOST_VER)"
      $env:BOOST_INCLUDEDIR="$($env:BOOST_ROOT)"
      $env:BOOST_LIBRARYDIR="$($env:BOOST_ROOT)/$($env:LIB_ARCHITECTURE)-msvc-$($env:VISUAL_STUDIO_VERSION)"

      $env:GENERATOR="$($env:GENERATOR)$($env:GENERATOR_SUFFIX)"

environment:
  matrix:
    - GENERATOR: "Visual Studio 14 2015"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VISUAL_STUDIO_VERSION: "14.0"
      BOOST_VER: 1_59_0
    - GENERATOR: "Visual Studio 15 2017"
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      VISUAL_STUDIO_VERSION: "15.0"
      BOOST_VER: 1_64_0

install:
  - ps: |
      python -m pip install --upgrade pip
      pip install mako six

before_build:
  - ps: |
      mkdir build
      cd build
      cmake --version
  - cmd: cmake .. -G "%GENERATOR%"

build_script:
   - msbuild ALL_BUILD.vcxproj /m /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
   - ps: ls ./

test_script:
  - ps: msbuild TEST.vcxproj /m /verbosity:normal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
